#!/usr/bin/env bash

# if [ "$EUID" -eq 0 ]; then
#     echo '/tmp/core.%h.%e.%p.%t' > /proc/sys/kernel/core_pattern
#     groupadd -g $USER_GID $USERNAME
#     useradd -m -u $USER_UID -g $USERNAME -s /bin/bash $USERNAME
#     exec setpriv --reuid=$USERNAME --regid=$USERNAME --clear-groups "$0" "$@"
# fi

cd /workspace

# git config --global --add safe.directory /workspace || true

# Start D-Bus session
eval $(dbus-launch --sh-syntax)

# Check for interactive flag
if [[ "${1:-}" == "-i" ]]; then
    exec bash
fi
